name: Run Scrapers Daily

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at 00:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scrapers
        run: |
          cd scrapers
          python run_scrapers.py
